replication:
  connections:
    - type: postgresql
      uri: !env PS_DATA_SOURCE_URI
      sslmode: disable

storage:
  type: postgresql
  uri: !env PS_STORAGE_URI
  sslmode: disable

port: 8080

sync_config:
  path: sync-config.yaml

client_auth:
  audience: ['schachterl']
  jwks:
    keys:
      - kty: RSA
        alg: RS256
        kid: dev-key-1
        e: 'AQAB'
        n: 'qxms1ecf5ft8lRyeTCj0dv0QUnyUfdEYfzCNHGDOMNPBfkrv4tYePhkVvPDiktcu95Mp0t8NukmYB5gBA6vk2b_KQLAd-wJU9DCjXiUkp1JHa4G2FBaXjIPhblsVT2bhUihz_YDu739Snx1Od12R5SoTXSnr5PvlfSpSdmc6f8syzDhGfQ9_nkB9TEnLDfkYFgvnR_TpbLxxL2WCLmUFFBjxCYE9QwRl1fudYlGFu3H-kG90wbPcHvRlKnsn4bu8MBWwJQTaxJk4RkgfTtPxZphTY7-9-mumaFZ2adUjgXnGA6lMa0qsxw4eocRpyJgsgsR7uKWgEsnbcvNsDH2How'
