replication:
  connections:
    - type: postgresql
      uri: !env PS_DATA_SOURCE_URI
      sslmode: disable

storage:
  type: postgresql
  uri: !env PS_STORAGE_URI
  sslmode: disable

port: 8080

sync_config:
  path: sync-config.yaml

client_auth:
  audience: ['schachterl']
  jwks:
    keys:
      - kty: RSA
        alg: RS256
        kid: dev-key-1
        e: 'AQAB'
        n: 'v-4vWnXgzOKjOm9O8_FVjVGnzcQik0VbcG8vkAiBIATaqXCwHxTuchgxUVEX0gt1Aj1xGWj4uoiFiGPOVDGOKxnSzfJQRsPvrXx_q2dczxdoLRGMpA3DRMNmQ-ncjQNmy6nmo3xB3zGHJtjsJJisGCC0RcDisbrcWv1cMJ1OW5dbBb2qjgWaUFY3PnjBFXeu-47hI1yxinTXCii7ostjZ7TikPuhuRWbXLMLtIY-_4mx95Ndr-bXDEZyorqQ3DS8pMIsYQxJeXYvsM7uj5XFehycvaVAKxS1aPbHYnHNP_7aPRj-RpYuBKKbVhvYaHfOcYqJAwodRhFKGKV03D2FfQ'
